/* Additional record code for ThermoFMU generated by the OpenModelica Compiler OpenModelica v1.22.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ThermoFMU_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

